//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRental.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleImage
    {
        public Nullable<int> VehicleId { get; set; }
        public string ImageUrl { get; set; }
        public int id { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
